# **Householder Notebook**

Maby by eti.calde

---

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from ipywidgets import interact, FloatSlider, Dropdown

## **1.1 Householder Reflection**

**Definition**
Given a unit vector $u$ defining a hyperplane perpendicular to ir, a Householder reflection over a vector $x$ is defined as:

$$
H_{\mathbf{u}}(x) = x-2 \langle \mathbf{x},\mathbf{u}\rangle \mathbf{u}
$$

Is nothing more that the vector reflected over the hyperplane. This can be expressed in matrix form as follows:

$$
H =(I-2\mathbf{u}^T\mathbf{u})
$$

---

## **1.2 let’s see the transformation in code!!**

In [16]:
def get_householder_matrix(v):
    """
    Calculates the Householder reflection matrix for a vector v
    
    Parameters
    ----------
    v : ndarray (n,), input vector.
    Returns
    -------
    H : ndarray (n,n), Householder reflection matrix.
    """
    v = v.reshape(-1, 1)
    I = np.eye(v.shape[0])
    return I - 2 * (v @ v.T) / (v.T @ v)

In [4]:
cmap = plt.get_cmap("magma")
C_V1   = cmap(0.15)  # x
C_V2   = cmap(0.35)  # u
C_PLN  = cmap(0.85)  # hyperplane
C_REF  = cmap(0.60)  # H(x)

def plot_householder(theta1_deg=30.0, theta2_deg=120.0, r1=1.5):
    # Parameters
    t1 = np.deg2rad(theta1_deg)
    t2 = np.deg2rad(theta2_deg)
    unitari_rad = 1.0

    # Vectors
    x = np.array([r1*np.cos(t1), r1*np.sin(t1)])
    u = np.array([unitari_rad*np.cos(t2), unitari_rad*np.sin(t2)])

    # Hyperplane
    n_perp = np.array([-u[1], u[0]])

    # Householder
    H = get_householder_matrix(u)
    x_householder = H @ x
    print("x:", x)
    print("x' (Householder):", x_householder)
    # ===================================================================
    # PLOT
    plt.figure()

    # Vectors
    plt.quiver(0, 0, x[0], x[1], color=C_V1, scale=1, scale_units='xy', angles='xy', label='x')
    plt.quiver(0, 0, u[0], u[1], color=C_V2, scale=1, scale_units='xy', angles='xy', label='u (unitario)')
    plt.quiver(0, 0, x_householder[0], x_householder[1],
               color=C_REF, scale=1, scale_units='xy', angles='xy', label='H(x)')
    # Hyperplane
    L = 2.2
    pts = np.vstack([-L*n_perp, L*n_perp])
    plt.plot(pts[:,0], pts[:,1], linestyle='--', color=C_PLN, label='Hip. u·x = 0')

    # Details
    lim = 2.2
    plt.xlim(-lim, lim); plt.ylim(-lim, lim)
    plt.grid(True)
    plt.gca().set_aspect('equal', adjustable='box')
    plt.legend()
    plt.title("Householder reflection of x")
    plt.show()

angle1 = FloatSlider(value=30.0,  min=0.0, max=360.0, step=1.0, description='Ángulo x (°)')
angle2 = FloatSlider(value=120.0, min=0.0, max=360.0, step=1.0, description='Ángulo u (°)')
len_r1 = FloatSlider(value=1.5,   min=0.0, max=2.0,   step=0.1, description='||x||')

interact(plot_householder, theta1_deg=angle1, theta2_deg=angle2, r1=len_r1)


interactive(children=(FloatSlider(value=30.0, description='Ángulo x (°)', max=360.0, step=1.0), FloatSlider(va…

<function __main__.plot_householder(theta1_deg=30.0, theta2_deg=120.0, r1=1.5)>

Now let's apply the Householder Reflection to get the QR factorization of a matrix $A$.

---

## **2.2 Get a random matrix**

In [5]:
def _random_orthogonal(n, rng):
    """Matriz ortogonal ~ Haar usando QR sobre una matriz gaussiana."""
    M = rng.standard_normal((n, n))
    Q, R = np.linalg.qr(M)
    # Asegurar unicidad de signos (evita que R tenga diag negativa)
    d = np.sign(np.diag(R))
    d[d == 0] = 1.0
    Q = Q * d
    return Q

def make_matrix_with_condition(n, kappa=10.0, structure="general", spectrum="geom", seed=None):
    """
    Crea una matriz A de tamaño n×n con número de condición ~kappa en norma 2.
    structure: "general" (no simétrica) o "spd" (simétrica definida positiva).
    spectrum:  "geom" reparte singular/propios en progresión geométrica entre [1/kappa, 1].
    """
    if kappa < 1:
        raise ValueError("kappa debe ser >= 1")
    rng = np.random.default_rng(seed)

    # Valores singulares/propios: de 1/kappa (mín) a 1 (máx)
    if spectrum == "geom":
        vals = np.geomspace(1.0, 1.0/kappa, num=n)  # descendente; max=1, min=1/kappa
        vals = np.sort(vals)[::-1]                  # garantizar orden descendente
    else:
        raise ValueError("spectrum no soportado (usa 'geom')")

    if structure == "general":
        U = _random_orthogonal(n, rng)
        V = _random_orthogonal(n, rng)
        A = U @ np.diag(vals) @ V.T
    elif structure == "spd":
        Q = _random_orthogonal(n, rng)
        A = Q @ np.diag(vals) @ Q.T   # simétrica y definida positiva
    else:
        raise ValueError("structure debe ser 'general' o 'spd'")

    # Reescala opcional: no cambia kappa; útil si quieres ||A|| ~ 1, etc.
    # A = A / np.linalg.norm(A, 2)

    # Verificación empírica (puede diferir ~1e-12 por redondeo)
    s = np.linalg.svd(A, compute_uv=False)
    kappa_emp = s[0] / s[-1]
    return A, kappa_emp

def generate_system(N, kappa=10.0, structure="general", seed=None, x_known=None):
    """
    Genera (A, x_true, b) con cond_2(A) ~ kappa.
    - N: tamaño
    - structure: 'general' o 'spd'
    - x_known: si lo pasas, se usa; si no, se crea aleatorio.
    """
    rng = np.random.default_rng(seed)
    A, kappa_emp = make_matrix_with_condition(N, kappa=kappa, structure=structure, seed=seed)
    if x_known is None:
        x_true = rng.standard_normal(N)
    else:
        x_true = np.asarray(x_known, dtype=float)
        if x_true.shape != (N,):
            raise ValueError("x_known debe tener shape (N,)")
    b = A @ x_true
    return A, x_true, b, kappa_emp


In [6]:
N = 5
kappa_deseada = 100
A, x_true, b, kappa_emp = generate_system(N, kappa=kappa_deseada, structure="general", seed=42)

print("condición objetivo:", kappa_deseada)
print("condición empírica:", kappa_emp)

x_rec = np.linalg.lstsq(A, b, rcond=None)[0]
print("error relativo en x:", np.linalg.norm(x_rec - x_true) / np.linalg.norm(x_true))
print("A =\n", A)
print("x_true =\n", x_true)
print("b =\n", b)

condición objetivo: 100
condición empírica: 100.00000000000038
error relativo en x: 3.0865966542260165e-15
A =
 [[-0.13081689  0.16657923  0.07723457 -0.03782061 -0.15396884]
 [ 0.11084154 -0.58528037 -0.33288669 -0.20974112 -0.0265564 ]
 [ 0.00141675  0.39448968  0.17665277  0.20730293  0.17369555]
 [ 0.08366047 -0.41891365 -0.20390799 -0.0688255   0.00174923]
 [-0.02311784 -0.02242665 -0.08526961 -0.13976344 -0.09035459]]
x_true =
 [ 0.30471708 -1.03998411  0.7504512   0.94056472 -1.95103519]
b =
 [ 0.10968479  0.24717976 -0.42116632  0.23998568 -0.00288329]


## **2.3 QR Factorization**

In [7]:
def get_Q_Matrix(householder_vectors):
    """
    Calculates Q matrix of QR factorization using Householder reflections.

    Parameters
    ----------
    householder_vectors : ndarray (n,n), Householder reflection vectors.
    each i-th column represents a Householder vector for the i-th step of the QR factorization.

    Returns
    -------
    Q : ndarray (n,n), Orthogonal matrix.
    """
    n = householder_vectors.shape[0]
    Q = np.eye(n)
    for i in range(n):
        u = householder_vectors[:n-i, i]
        H_tilde = get_householder_matrix(u)
        H_full = np.eye(n)
        H_full[i:, i:] = H_tilde
        Q = Q @ H_full
    return Q

def QR_Householder(A):
    """
    QR factorization using Householder reflections.

    Parameters
    ----------
    A : ndarray (n,n), input matrix.
    Returns
    -------
    Q,R : ndarray (n,n), Orthogonal matrix and upper triangular matrix.
    """
    if (A.shape[1] != A.shape[0]):
        print("Matrix is not square")
        return None, None
    
    n = A.shape[0]
    # We need to work with submatrices of A
    # and we don't want to modify the original Matrix
    A = A.copy()

    # Each Householder vector is 1 dimension smaller than the previous one,
    # So we use just the first n-i rows on each iteration 
    householder_vectors = np.zeros((n, n))

    for i in range(n):
        sub_A = A[i:, i:]
        # Get Column i of A
        col_i_of_A = sub_A[:,0]
        col_i_of_A = col_i_of_A.reshape(-1,1)

        # Compute the Householder vector
        alpha = -np.sign(col_i_of_A[0,0]) * np.linalg.norm(col_i_of_A)
        e1 = np.eye(col_i_of_A.shape[0])[:,0].reshape(-1,1)
        u = col_i_of_A - alpha * e1
        u = u / np.linalg.norm(u)
        # print(f"u en la iteracion {i}, {u.shape} =\n", u)

        # Save the Householder vector
        householder_vectors[0:n-i,i] = u.ravel()
        # print(f"holder_vectors en la iteracion {i} =\n", holder_vectors)
        
        # FIX RESPECTO A LA VERSIÓN DE LA CALSE ANTERIOR.
        A[i:, i:] -= 2 * np.outer(u, u.T @ A[i:, i:])

    Q = get_Q_Matrix(householder_vectors)
    R = np.triu(A)
    # R = A
    return Q,R

Q,R = QR_Householder(A)
# print("uni?:\n", Q.T@Q)
compare_numpy = True
if (N <= 5):
    # print("A =\n", A)
    print("R:\n", R)
    print("Reconstrucción ||A - Q R|| =", np.linalg.norm(A - Q @ R))
    if compare_numpy:
        A_np, Q_np, R_np = A.copy(), Q.copy(), R.copy()
        print("Comparando con numpy...")
        Q_np, R_np = np.linalg.qr(A_np)
        print("R (numpy):\n", R_np)
        print("Reconstrucción ||A - Q R|| =", np.linalg.norm(A_np - Q_np @ R_np))
else:
    print("Reconstrucción ||A - Q R|| =", np.linalg.norm(A - Q @ R))
    if compare_numpy:
        A_np, Q_np, R_np = A.copy(), Q.copy(), R.copy()
        print("Comparando con numpy...")
        Q_np, R_np = np.linalg.qr(A_np)
        print("Reconstrucción ||A - Q R|| =", np.linalg.norm(A_np - Q_np @ R_np))

R:
 [[ 0.1921833  -0.62770239 -0.32176976 -0.10684436  0.10239912]
 [ 0.          0.55489204  0.29328574  0.29399594  0.22344126]
 [ 0.          0.          0.08533463  0.10391032  0.02808917]
 [ 0.          0.          0.         -0.06340605 -0.03532516]
 [ 0.          0.          0.          0.          0.01733085]]
Reconstrucción ||A - Q R|| = 2.2187937202187573e-16
Comparando con numpy...
R (numpy):
 [[ 0.1921833  -0.62770239 -0.32176976 -0.10684436  0.10239912]
 [ 0.          0.55489204  0.29328574  0.29399594  0.22344126]
 [ 0.          0.          0.08533463  0.10391032  0.02808917]
 [ 0.          0.          0.         -0.06340605 -0.03532516]
 [ 0.          0.          0.          0.         -0.01733085]]
Reconstrucción ||A - Q R|| = 2.275337170545401e-16


## **2.4 Arnoldi Householder**

Partimos de un sistema:
$$
A x = b
$$

Donde podemos definir el primer vector ortonormalizado:

$$
q_1 = \frac{b}{\| b \|}
$$

Y en base a ese sistema se puede obtener el sub-espacio de Krylov de la matriz A:
$$
\begin{align*}
\mathcal{K}(A,b) = \{b, Ab, A^2 b, ...\}
\end{align*}
$$

La cual tiene el mismo span que las bases ortonormalizadas:
$$
\begin{align*}
\mathcal{K}(A,b) &= \text{span}\{b, Ab, A^2 b, ...\} \\
                 &= \text{span}\{q_1, q_2, q_3, ...\} \\
                 &= \text{span}\{q_1, Aq_1, Aq_2, ...\}

\end{align*}
$$


El obejtivo de la iteración de Arnoldi es obtener una base ortonormalizada, a partir la base de Krylov:
$$
Q = \{q_1, q_2, q_3,...\}
$$

Donde se tiene la relación fundamental:
$$
A Q_m = Q_{m+1} H_m
$$

Donde $H$ es la matriz de Hessenberg de dimensiones $(m+1) \times m$


In [17]:
def householder_to_e1(vec):
    """
    return the u vector such that:
    Hu(vec) = ||vec||*e1
    where Hu is the Householder reflection matrix defined by u.

    Parameters
    ----------
    vec : ndarray (n,1), input vector.
    Returns
    -------
    u : ndarray (n,1), Householder vector.
    """
    n = vec.shape[0]
    v = vec.copy().reshape(-1,1)

    alpha = -np.sign(v[0]) * np.linalg.norm(v)
    e1 = np.zeros((n,1))
    e1[0] = 1.0
    u = v - alpha * e1
    u = u / np.linalg.norm(u)
    return u 

In [20]:
random_vec = np.random.randn(5)
print("random_vec =", random_vec)

u1 = householder_to_e1(random_vec)
print("u1 =", u1)

H1 = get_householder_matrix(u1)
print("H1 =\n", H1)

a1_transformed = H1 @ random_vec
print("H1 @ random_vec:\n",a1_transformed)


random_vec = [-0.29875723 -0.23396487  1.62001375 -1.07951432  0.47718126]
u1 = [[-0.75711674]
 [-0.07574138]
 [ 0.52444659]
 [-0.34947086]
 [ 0.15447776]]
H1 =
 [[-0.1464515  -0.11469013  0.79413459 -0.52918048  0.23391539]
 [-0.11469013  0.98852649  0.07944462 -0.05293881  0.02340072]
 [ 0.79413459  0.07944462  0.44991154  0.36655761 -0.16203067]
 [-0.52918048 -0.05293881  0.36655761  0.75574023  0.10797095]
 [ 0.23391539  0.02340072 -0.16203067  0.10797095  0.95227325]]
H1 @ random_vec:
 [ 2.03997380e+00  0.00000000e+00 -3.33066907e-16  2.22044605e-16
 -1.66533454e-16]


In [30]:
def Arnoldi_Householder(A,b):
    n = A.shape[0]
    A = np.copy(A)

    # First vector
    a1 = A[:,0]
    # print("a1 =", a1)
    sub_a1 = a1[1:]
    # print("sub_a1 =", sub_a1)
    u1 = householder_to_e1(sub_a1)
    H1_tilde = get_householder_matrix(u1)
    H1 = np.eye(n)
    H1[1:, 1:] = H1_tilde

    # Update A
    A = H1 @ A
    print("A after H1:\n", A)

    # second vector
    a2 = A[:,1]
    sub_a2 = a2[2:]
    u2 = householder_to_e1(sub_a2)
    H2_tilde = get_householder_matrix(u2)
    H2 = np.eye(n)
    H2[2:, 2:] = H2_tilde

    # Update A
    A = H2 @ A
    print("A after H2:\n", A)

    # Compute Q
    Q = H2 @ H1
    print("Q:\n", Q)

    print("is Q orthogonal?:\n", Q.T @ Q)
    return Q, A
N = 4
kappa_deseada = 3
A, x_true, b, kappa_emp = generate_system(N, kappa=kappa_deseada, structure="general", seed=42)
Q, H = Arnoldi_Householder(A,b)

print("check arnoldi A @ Q = Q @ H", np.linalg.norm(A @ Q - Q @ H))
print("A =\n", A)
print("x_true =\n", x_true)
print("b =\n", b)

A after H1:
 [[ 3.57508435e-01  4.10353371e-01 -7.90674036e-02  5.28021252e-02]
 [ 6.71264082e-01 -1.83547661e-01 -2.76086926e-01  2.18464903e-01]
 [ 6.93889390e-18  2.44523304e-01  5.45600294e-01 -5.40490810e-02]
 [ 0.00000000e+00 -1.57814832e-01 -2.82017276e-01  6.66836931e-01]]
A after H2:
 [[ 3.57508435e-01  4.10353371e-01 -7.90674036e-02  5.28021252e-02]
 [ 6.71264082e-01 -1.83547661e-01 -2.76086926e-01  2.18464903e-01]
 [-5.83010075e-18 -2.91027778e-01 -6.11345408e-01  4.07016193e-01]
 [ 3.76273490e-18  0.00000000e+00  5.89085442e-02  5.30971388e-01]]
Q:
 [[ 1.          0.          0.          0.        ]
 [ 0.         -0.70823159  0.41839545 -0.5686416 ]
 [ 0.         -0.65989411 -0.67857886  0.32259958]
 [ 0.         -0.25089397  0.60371846  0.75668768]]
is Q orthogonal?:
 [[ 1.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  1.00000000e+00 -2.77555756e-17  2.77555756e-17]
 [ 0.00000000e+00 -2.77555756e-17  1.00000000e+00  5.55111512e-17]
 [ 0.00