In [1]:
import numpy as np

### Rank-1 matrices

$$
A = uv^{T} = 
\begin{bmatrix}
-  & u_{0}v^{T} & -\\
-  & u_{1}v^{T} & -\\
& \vdots &\\
-  & u_{n}v^{T} & -\\
\end{bmatrix} = 
\begin{bmatrix}
| & | &  & |\\
v_0u & v_2u & \dots & v_nu\\
| & | &  & |\\

\end{bmatrix}

$$

In [ ]:
u = np.array([1,2,3,4]).T
# v = np.eye(3) + np.eye(3, k=1)
v = np.array([1,1,1])



ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [ ]:
np.vstack([
u[0,:] @ v.T,
u[1,:] @ v.T,
u[2,:] @ v.T
])


array([[ 3.,  5.,  3.],
       [ 9., 11.,  6.],
       [15., 17.,  9.]])

In [31]:
u

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
v

array([[1., 1., 0.],
       [0., 1., 1.],
       [0., 0., 1.]])

In [ ]:
v[:,0] @ 

array([1., 4., 7.])