In [5]:
import numpy as np
import scipy.sparse as sp


In [20]:
# construcción de una matriz sparse simetrica y definida positiva.

def construir_spd_densa(n,densidad):
    A = sp.random_array((n,n),density=densidad, format='csr', dtype=float) 
    tau = 1e-2
    return (A.T @ A) + tau * sp.eye(n, format='csr').toarray()
def nnz_lower(M, tol=1e-14):
    Ml = np.tril(M)
    return int(np.count_nonzero(np.abs(Ml) > tol))
tol = 1e-14
def cholesky_in(A):
    n = A.shape[0]
    L = np.zeros_like(A)

    for i in range(n):
        for j in range(i+1):
      
            if j < i and A[i, j] == 0:
                L[i, j] = 0.0  
                continue
            s = 0.0
            for k in range(j):
                s += L[i, k] * L[j, k]
            if i == j:

                L[i, j] = (A[i, i] - s) ** 0.5
            else:
                L[i, j] = (A[i, j] - s) / L[j, j]

    return L
def cholesky(A):
    n = A.shape[0]
    L = np.zeros_like(A)
    for i in range(n):
        for j in range(i+1):
            s = 0
            for k in range(j):
                s += L[i][k] * L[j][k]

            if (i == j):
                L[i][j] = (A[i][i] - s) ** 0.5
            else:
                L[i][j] = (1.0 / L[j][j] * (A[i][j] - s))
    return L

In [21]:
B = construir_spd_densa(5,0.5)
B

array([[0.70837797, 1.0609201 , 0.        , 0.24837538, 0.        ],
       [1.0609201 , 1.904666  , 0.25109846, 0.33166573, 0.        ],
       [0.        , 0.25109846, 0.85759625, 0.        , 0.        ],
       [0.24837538, 0.33166573, 0.        , 0.17550119, 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.01      ]])

In [22]:

cholb = np.linalg.cholesky(B)
cholb

array([[ 0.84165193,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.2605212 ,  0.56191842,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.44685929,  0.81111838,  0.        ,  0.        ],
       [ 0.29510463, -0.07175404,  0.03953055,  0.28583761,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.1       ]])

In [24]:
chol = cholesky(B)
print(np.linalg.norm( B - chol@chol.T))

1.571009851008036e-16


In [25]:
cholb = cholesky_in(B)


print(np.linalg.norm( B - cholb@cholb.T))

0.0453452830900769


In [29]:
A = np.array([
    [ 5, -2,  0, -2, -2],
    [-2,  5, -2,  0,  0],
    [ 0, -2,  5, -2,  0],
    [-2,  0, -2,  5, -2],
    [-2,  0,  0, -2,  5]
], dtype=float) 
print(np.linalg.cholesky(A))
cholesky_in(A)


[[ 2.23606798  0.          0.          0.          0.        ]
 [-0.89442719  2.04939015  0.          0.          0.        ]
 [ 0.         -0.97590007  2.01186954  0.          0.        ]
 [-0.89442719 -0.39036003 -1.18345267  1.62697843  0.        ]
 [-0.89442719 -0.39036003 -0.18935243 -1.95237412  0.4472136 ]]


array([[ 2.23606798,  0.        ,  0.        ,  0.        ,  0.        ],
       [-0.89442719,  2.04939015,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.97590007,  2.01186954,  0.        ,  0.        ],
       [-0.89442719,  0.        , -0.99410024,  1.7921397 ,  0.        ],
       [-0.89442719,  0.        ,  0.        , -1.5623782 ,  1.32626331]])

In [ ]:
B = construir_spd_densa(500,0.5)
cholb = np.linalg.cholesky(B)
print("nnz_lower(B) =", nnz_lower(B))
print("nnz_lower(L) =", nnz_lower(cholb))
print("fill-in abs  =", nnz_lower(cholb, tol) - nnz_lower(B, tol))

nnz_lower(B) = 125250
nnz_lower(L) = 125250
fill-in abs  = 0


In [27]:
for n in [5,10,50,80,100]:
    for d in [0.1,0.2,0.3,0.4, 0.5]:
        print(n,d)
        B = construir_spd_densa(n,d)
        cholb = np.linalg.cholesky(B)
        nnz_lower(cholb, tol) - nnz_lower(B, tol)
        print("nnz_lower(B) =", nnz_lower(B))
        print("nnz_lower(L) =", nnz_lower(cholb))
        print("fill-in abs  =", nnz_lower(cholb, tol) - nnz_lower(B, tol))
        print()

5 0.1
nnz_lower(B) = 5
nnz_lower(L) = 5
fill-in abs  = 0

5 0.2
nnz_lower(B) = 7
nnz_lower(L) = 7
fill-in abs  = 0

5 0.3
nnz_lower(B) = 10
nnz_lower(L) = 11
fill-in abs  = 1

5 0.4
nnz_lower(B) = 11
nnz_lower(L) = 13
fill-in abs  = 2

5 0.5
nnz_lower(B) = 13
nnz_lower(L) = 13
fill-in abs  = 0

10 0.1
nnz_lower(B) = 13
nnz_lower(L) = 13
fill-in abs  = 0

10 0.2
nnz_lower(B) = 28
nnz_lower(L) = 32
fill-in abs  = 4

10 0.3
nnz_lower(B) = 36
nnz_lower(L) = 43
fill-in abs  = 7

10 0.4
nnz_lower(B) = 50
nnz_lower(L) = 54
fill-in abs  = 4

10 0.5
nnz_lower(B) = 51
nnz_lower(L) = 55
fill-in abs  = 4

50 0.1
nnz_lower(B) = 533
nnz_lower(L) = 1130
fill-in abs  = 597

50 0.2
nnz_lower(B) = 1147
nnz_lower(L) = 1266
fill-in abs  = 119

50 0.3
nnz_lower(B) = 1259
nnz_lower(L) = 1267
fill-in abs  = 8

50 0.4
nnz_lower(B) = 1275
nnz_lower(L) = 1275
fill-in abs  = 0

50 0.5
nnz_lower(B) = 1275
nnz_lower(L) = 1275
fill-in abs  = 0

80 0.1
nnz_lower(B) = 1840
nnz_lower(L) = 3147
fill-in abs  = 1307

80 

In [ ]:
# todo graficos de los nnz
# todo verificar con matriz de wikpedia